### ISSUE TITLE
How do I await the request in JavaScript?

### ISSUE THREAD

**Issue by barryofguilder** [NullVoxPopuli/ember-data-resources#326]
I have a component and in the constructor, I'm trying to find the selected record from the `ember-data-resource` result. When I perform the `find`, the data hasn't loaded yet, so I get an `undefined`. How do I await the data request so that I can do something with the data.

Here is a small code example of what I'm trying to do:
```typescript
constructor() {
  super();

  const geoId = this.args.filters.geoId;

  if (geoId) {
    // `this.geosData.records` is always `undefined` here.
    const geo = this.geosData.records?.find((geo) => geo.id === geoId);

    if (geo) {
      this.selectedGeo = geo;
    }
  }
}
```

**Comment by barryofguilder** [comment]
Something like this is what I'm wondering if its possible:

```javascript
async function initializeGeoFilter() {
  const geoId = this.args.filters.geoId;

  if (geoId) {
    // I would like to be able to `await` the API call so I can use it on the next line.
    const geoRecords = await this.geosData.records;
    const geo = geoRecords?.find((geo) => geo.id === geoId);

    if (geo) {
      this.selectedGeo = geo;
    }
  }
}

```

**Comment by NullVoxPopuli** [comment]
There isn't an API for this because it would opt you out of reactivity (promises disconnect from auto-tracking).

Instead, I think you may want a _define_ what `selectedGeo` is.

For example:
```js
class Demo X {
  @tracked _selectedGeo;

  get selectedGeo() {
    return this._selectedGeo || this.defaultGeo
  }
  set selectedGeo(value) {
    this._selectedGeo = value;
  }

  get defaultGeo() {
    const geoId = this.args.filters.geoId;

    if (geoId) {
      const geoRecords = this.geosData.records || [];
      const geo = geoRecords?.find((geo) => geo.id === geoId);

      return geo;
    }

    // no default yet.
    return
  }
}
```

This reason being is that you have to handle how you want loading state to be represented.
With derived data, it's a bit forced, but with async functions, it's hidden, so it's easily forgotten.
Invoking async functions from the constructor leaves a lot of state "unmanaged", and can lead to subtle bugs, in my experience.

**Comment by barryofguilder** [comment]
Thanks for the explanation. Your example totally works in my situation.
